### ISSUE TITLE
deploying to forge from travis / broken regex…

### ISSUE THREAD

**Issue by igalic** [maestrodev/puppet-blacksmith#19]
hi folks,

we're trying to make blacksmith deploy to the forge whenever we create a new tag.
a couple of issues…

first off, it appears that the puppet module must already exist on the forge.
i might have to talk to @ryanycoleman about this one…

second, and perhaps more importantly right now:

in our puppetcommunity-extlib blacksmith is looking for [(?-mix:^puppet-extlib-.*\.tar\.gz$)](https://travis-ci.org/puppet-community/puppetcommunity-extlib/jobs/54558556#L180) and, failing to find it. which kinda makes sense, since the "author" is puppetcommunity…

what am i missing here?

**Comment by carlossg** [comment]
wrong username in `~/.puppetforge.yml` ? should be `puppetcommunity` instead of `puppet`

**Comment by igalic** [comment]
heh, yeah, no, we got the /puppet space in the forge :3

**Comment by daenney** [comment]
Oh yeah, so that's going to be a bit confusion. Modules from Puppet vs modules from Puppetlabs :smile:.

**Comment by nibalizer** [comment]
Yep author in metadata.json will need to be puppet

**Comment by igalic** [comment]
hrm… should we rename our repository to puppet- to match that also?

**Comment by nibalizer** [comment]
/me shrug. I think we can let the module names float for a while. If after we get a lot of modules we want to do a 'great renaming to be consistent' we can do that then.

**Comment by igalic** [comment]
*nod*

**Comment by igalic** [comment]
closing this, in favour of https://github.com/puppet-community/puppetcommunity-extlib/issues/10
