### ISSUE TITLE
Client ID and client secret do not match.

### ISSUE THREAD

**Issue by hajee** [maestrodev/puppet-blacksmith#20]
It worked fine before. But now I get the error:

```
Blacksmith::Error: Error login to the forge https://forgeapi.puppetlabs.com as hajee [401 Unauthorized]: Client ID and client secret do not match.
```

I suspect the OAUTH [credentials](https://github.com/maestrodev/puppet-blacksmith/blob/master/lib/puppet_blacksmith/credentials.yml) are expired.

I'm using version 3.3.1

**Comment by carlossg** [comment]
Works fine here

**Comment by hajee** [comment]
Works fine here now as well. Must have been something on the forge server. Thanks for taking the time to investigate.
